// src/pages/AboutUs/AboutCompany/index.jsx
import SubjectSummary from '@/pages/AboutUs/AboutCompany/SubjectSummary';
import OurAdvantage from '@/pages/AboutUs/AboutCompany/OurAdvantage';
import OurVision from '@/pages/AboutUs/AboutCompany/OurVision';
import CooperationCompany from '@/pages/AboutUs/AboutCompany/CooperationCompany';
import './index.less';

const AboutCompany = {
  render() {
    return (
      <div>
        <SubjectSummary />
        <CooperationCompany />
        <OurAdvantage />
        <OurVision />
      </div>
    );
  },
};

export default AboutCompany;

// src/pages/AboutUs/AboutCompany/index.vue
<template>
  <div>
    <SubjectSummary />
    <OurAdvantage />
    <CooperationCompany />
    <OurVision />
  </div>
</template>

<script>
import SubjectSummary from '@/pages/AboutUs/AboutCompany/SubjectSummary';
import OurAdvantage from '@/pages/AboutUs/AboutCompany/OurAdvantage';
import OurVision from '@/pages/AboutUs/AboutCompany/OurVision';
import CooperationCompany from '@/pages/AboutUs/AboutCompany/CooperationCompany';

export default {
  components: {
    SubjectSummary,
    OurAdvantage,
    OurVision,
    CooperationCompany,
  },
  data() {
    return {};
  },
  methods: {},
};
</script>

<style lang="less" scoped>
@import './index.less';
</style>
